version: "3.8"

services:
  airflow:
    image: apache/airflow:2.9.3
    container_name: airflow
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/project/src
      - ./scripts:/opt/project/scripts
      - ./data:/opt/project/data
    ports:
      - "8080:8080"
    command: >
      bash -lc "
      airflow db migrate &&
      airflow users create
        --username admin --password admin
        --firstname Admin --lastname User
        --role Admin --email admin@example.com || true &&
      airflow webserver & airflow scheduler
      "
